name: Branch Name Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: lekterable/branchlint-action@2.1.0
        with:
          allowed: |
            /^feature_[a-zA-Z0-9_\-]+$/
            /^fix_[a-zA-Z0-9_\-]+$/
            main
          errorMessage: "❌ Le nom de la branche doit commencer par 'feature_' ou 'fix_' (ex: feature_login, fix_bug123)."
