name: Dependabot Auto-approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-validate:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test backend build
        run: |
          echo "Testing backend build..."
          npm run test
          echo "✅ Build successful"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Check update type
        id: check-update
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Détecter le type de mise à jour
          if [[ "$PR_TITLE" =~ (minor|patch) ]]; then
            echo "safe_update=true" >> $GITHUB_OUTPUT
            echo "✅ Safe update detected: $PR_TITLE"
          else
            echo "safe_update=false" >> $GITHUB_OUTPUT
            echo "⚠️ Major update detected: $PR_TITLE"
          fi

      - name: Create Dependabot issue
        run: |
          PACKAGE_NAME=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'bump \K[^\s]+')
          ISSUE_TITLE="📦 Mise à jour Dependabot: $PACKAGE_NAME"
          ISSUE_BODY="## 🤖 Mise à jour automatique Dependabot
          
          **Package concerné:** \`$PACKAGE_NAME\`
          **Pull Request:** #${{ github.event.pull_request.number }}
          **Créée automatiquement par:** Dependabot
          
          ### 🔗 Liens utiles:
          - [Pull Request](${{ github.event.pull_request.html_url }})
          - [Détails Dependabot](${{ github.event.pull_request.html_url }}/files)
          
          **⚠️ Cette issue sera fermée automatiquement quand la PR sera mergée.**"
          
          gh issue create \
            --title "$ISSUE_TITLE" \
            --body "$ISSUE_BODY" \
            --label "dependabot" \
            --milestone "dependabot" \
            --assignee "ttmartinks"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Auto-approve safe updates
        if: steps.check-update.outputs.safe_update == 'true'
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}"
          echo "✅ Auto-approved safe dependency update"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Comment on major updates
        if: steps.check-update.outputs.safe_update == 'false'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🚨 **Mise à jour majeure détectée** - Révision manuelle requise avant merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job pour fermer automatiquement l'issue quand la PR est mergée
  close-dependabot-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.actor == 'dependabot[bot]'
    
    steps:
      - name: Close related Dependabot issue
        run: |
          PACKAGE_NAME=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'bump \K[^\s]+')
          
          # Chercher l'issue correspondante et la fermer
          ISSUE_NUMBER=$(gh issue list --label "dependabot" --state open --search "$PACKAGE_NAME" --json number --jq '.[0].number')
          
          if [ ! -z "$ISSUE_NUMBER" ] && [ "$ISSUE_NUMBER" != "null" ]; then
            gh issue close $ISSUE_NUMBER --comment "✅ Mise à jour appliquée - PR #${{ github.event.pull_request.number }} mergée avec succès"
            echo "✅ Issue #$ISSUE_NUMBER fermée automatiquement"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
